import { StylesAndColorsData } from "./IStylesAndColors";

export const hairstyleData: StylesAndColorsData[] = [
  {
    number: "1",
    title: "Bob",
    colors: [
      "platinum",
      "blonde",
      "caramel",
      "brown",
      "black",
      "ginger",
      "green",
      "pink",
      "blue",
      "red",
    ],
  },
  {
    number: "2",
    title: "Blonde fringe",
    colors: [
      "platinum",
      "blonde",
      "caramel",
      "brown",
      "black",
      "ginger",
      "green",
      "pink",
      "blue",
      "red",
    ],
  },
  {
    number: "3",
    title: "Blonde fringe",
    colors: [
      "platinum",
      "blonde",
      "caramel",
      "brown",
      "black",
      "ginger",
      "green",
      "pink",
      "blue",
      "red",
    ],
  },
  {
    number: "4",
    title: "Blonde fringe",
    colors: [
      "platinum",
      "blonde",
      "caramel",
      "brown",
      "black",
      "ginger",
      "green",
      "pink",
      "blue",
      "red",
    ],
  },
  {
    number: "5",
    title: "Blonde fringe",
    colors: [
      "platinum",
      "blonde",
      "caramel",
      "brown",
      "black",
      "ginger",
      "green",
      "pink",
      "blue",
      "red",
    ],
    pose: 1,
  },
  {
    number: "6",
    title: "Blonde fringe",
    colors: [
      "platinum",
      "blonde",
      "caramel",
      "brown",
      "black",
      "ginger",
      "green",
      "pink",
      "blue",
      "red",
    ],
    pose: 1,
  },
  {
    number: "7",
    title: "Blonde fringe",
    colors: [
      "platinum",
      "blonde",
      "caramel",
      "brown",
      "black",
      "ginger",
      "green",
      "pink",
      "blue",
      "red",
    ],
    pose: 1,
  },
  {
    number: "8",
    title: "Blonde fringe",
    colors: [
      "platinum",
      "blonde",
      "caramel",
      "brown",
      "black",
      "ginger",
      "green",
      "pink",
      "blue",
      "red",
    ],
    pose: 1,
  },
];
