import { StylesAndColorsData } from './IStylesAndColors';

export const hairstyleData: StylesAndColorsData[] = [
  {
    number: '1',
    title: 'Bob',
    colors: [
      'platinum',
      'blonde',
      'caramel',
      'brown',
      'black',
      'ginger',
      'green',
      'pink',
      'blue',
      'red',
    ],
    purchased: true,
  },
  {
    number: '2',
    title: 'Long straight',
    colors: [
      'platinum',
      'blonde',
      'caramel',
      'brown',
      'black',
      'ginger',
      'green',
      'pink',
      'blue',
      'red',
    ],
    purchased: true,
  },
  {
    number: '3',
    title: 'Long curly',
    colors: [
      'platinum',
      'blonde',
      'caramel',
      'brown',
      'black',
      'ginger',
      'green',
      'pink',
      'blue',
      'red',
    ],
    purchased: true,
  },
  {
    number: '4',
    title: 'Messy bun',
    colors: [
      'platinum',
      'blonde',
      'caramel',
      'brown',
      'black',
      'ginger',
      'green',
      'pink',
      'blue',
      'red',
    ],

    purchased: true,
  },
  {
    number: '5',
    title: 'Lindsay',
    colors: [
      'platinum',
      'blonde',
      'caramel',
      'brown',
      'black',
      'ginger',
      'green',
      'pink',
      'blue',
      'red',
    ],
    purchased: true,
    pose: 1,
  },
  {
    number: '6',
    title: 'Long straight bangs',
    colors: [
      'platinum',
      'blonde',
      'caramel',
      'brown',
      'black',
      'ginger',
      'green',
      'pink',
      'blue',
      'red',
    ],
    purchased: true,
    pose: 1,
  },
  {
    number: '7',
    title: 'Low Ponytail',
    colors: [
      'platinum',
      'blonde',
      'caramel',
      'brown',
      'black',
      'ginger',
      'green',
      'pink',
      'blue',
      'red',
    ],
    purchased: true,
    pose: 1,
  },
  {
    number: '8',
    title: 'Blonde fringe',
    colors: [
      'platinum',
      'blonde',
      'caramel',
      'brown',
      'black',
      'ginger',
      'green',
      'pink',
      'blue',
      'red',
    ],
    purchased: true,
    pose: 1,
  },
];
