import { StylesAndColorsData } from "./IStylesAndColors";

export const topstyleData: StylesAndColorsData[] = [
  {
    number: "1",
    title: "yoga top",
    colors: [
      "blue",
      "green",
      "black",
      "yellow",
      "red",
      "hotpink",
      "pastelpink",
      "purple",
    ],
    pose: 1,
  },
  {
    number: "2",
    title: "boatstyle",
    colors: [
      "blue",
      "green",
      "black",
      "yellow",
      "red",
      "hotpink",
      "pastelpink",
      "purple",
    ],
    pose: 2,
  },
  {
    number: "3",
    title: "Lindsay",
    colors: [
      "blue",
      "green",
      "black",
      "yellow",
      "red",
      "hotpink",
      "pastelpink",
      "purple",
    ],
    pose: 1,
  },
  {
    number: "4",
    title: "stripes",
    colors: [
      "blue",
      "green",
      "black",
      "yellow",
      "red",
      "hotpink",
      "pastelpink",
      "purple",
    ],
    pose: 2,
  },
  {
    number: "5",
    title: "Mean girls hoodie",
    colors: ["blue", "green", "black", "beige", "hotpink", "purple"],
    pose: 2,
  },
  {
    number: "6",
    title: "Bikini top",
    colors: [
      "blue",
      "green",
      "black",
      "yellow",
      "red",
      "hotpink",
      "pastelpink",
      "purple",
    ],
    pose: 3,
  },
  {
    number: "7",
    title: "Jeans jacket",
    colors: ["blue", "lightblue", "grey", "black", "white"],
    pose: 2,
  },
  {
    number: "8",
    title: "scuba funnel",
    colors: [
      "blue",
      "green",
      "black",
      "yellow",
      "grey",
      "red",
      "hotpink",
      "pastelpink",
      "black",
    ],
    pose: 1,
  },
];
