import { StylesAndColorsData } from './IStylesAndColors';

export const topstyleData: StylesAndColorsData[] = [
  {
    number: '1',
    title: 'yoga top',
    colors: [
      'blue',
      'green',
      'black',
      'yellow',
      'red',
      'hotpink',
      'lightpink',
      'purple',
    ],
    purchased: true,
    pose: 1,
  },
  {
    number: '2',
    title: 'boatstyle',
    colors: [
      'blue',
      'green',
      'black',
      'yellow',
      'red',
      'hotpink',
      'lightpink',
      'purple',
    ],
    purchased: true,
    pose: 2,
  },
  {
    number: '3',
    title: 'Lindsay',
    colors: [
      'blue',
      'green',
      'black',
      'yellow',
      'red',
      'hotpink',
      'lightpink',
      'purple',
    ],
    purchased: true,
    pose: 1,
  },
  {
    number: '4',
    title: 'Stripey shirt',
    colors: [
      'blue',
      'green',
      'black',
      'yellow',
      'red',
      'hotpink',
      'lightpink',
      'purple',
    ],
    pose: 2,
    purchased: true,
  },
];

export const SHOPtopstyleData: StylesAndColorsData[] = [
  {
    number: '5',
    title: 'Mean girls hoodie',
    colors: ['blue', 'green', 'black', 'beige', 'hotpink', 'purple'],
    pose: 2,
    purchased: false,
    SHOPimage: './shopImages/mean1.png',
  },
  {
    number: '6',
    title: 'Bikini top',
    colors: [
      'blue',
      'green',
      'black',
      'yellow',
      'red',
      'hotpink',
      'lightpink',
      'purple',
    ],
    pose: 3,
    purchased: false,
    SHOPimage: './shopImages/bikini.png',
  },
  {
    number: '7',
    title: 'Jeans jacket',
    colors: ['blue', 'lightblue', 'grey', 'black', 'white'],
    pose: 2,
    purchased: false,
    SHOPimage: './shopImages/jeansjacka.png',
  },
  {
    number: '8',
    title: 'Scuba funnel neck',
    colors: [
      'blue',
      'green',
      'black',
      'yellow',
      'grey',
      'red',
      'hotpink',
      'lightpink',
      'black',
    ],
    pose: 1,
    purchased: false,
    SHOPimage: './shopImages/scuba.png',
  },
  {
    number: '9',
    title: 'Dive Dress Top',
    colors: ['blue', 'black', 'red', 'hotpink', 'turqoise', 'yellow'],
    pose: 1,
    purchased: false,
  },
];
